function [mbqTrain, mbqVal, mbqTest] = makeVoltageMBQs(train_ds, val_ds, test_ds, miniBatchSize)
% MATLAB magic: Format as "SSTBC" to get 32(S) × 31(S) × 1(C) × 16(B) × 39(T)
mbqTrain = minibatchqueue(train_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=["SSTBC" "CB"], ...
    OutputEnvironment=["auto" "auto"]);
mbqVal = minibatchqueue(val_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=["SSTBC" "CB"], ...
    OutputEnvironment=["auto" "auto"]);
mbqTest = minibatchqueue(test_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=["SSTBC" "CB"], ...
    OutputEnvironment=["auto" "auto"]);
end