function [mbqTrain, mbqVal, mbqTest] = makeMBQs(train_ds, val_ds, test_ds, miniBatchSize, format)
% MATLAB magic: Format as "SSSTBC" to get 48(S) × 48(S) x 2(S) × 1(C) × n(B) × 39(T)
mbqTrain = minibatchqueue(train_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=[format "BC"], ...
    OutputEnvironment=["auto" "auto"]);
mbqVal = minibatchqueue(val_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=[format "BC"], ...
    OutputEnvironment=["auto" "auto"]);
mbqTest = minibatchqueue(test_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=[format "BC"], ...
    OutputEnvironment=["auto" "auto"]);
end