function [mbqTrain, mbqVal, mbqTest] = makeMBQs(train_ds, val_ds, test_ds, miniBatchSize, format_x, format_y)

% MATLAB magic: Format as "SSSTBC" to get 48(S) × 48(S) x 2(S) × 1(C) × n(B) × n(T)
mbqTrain = minibatchqueue(train_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFcn=@(x, y) makeOneHotSeqs(x, y), ...
    MiniBatchFormat=[format_x format_y], ...
    OutputEnvironment=["auto" "auto"]);
mbqVal = minibatchqueue(val_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFcn=@(x, y) makeOneHotSeqs(x, y), ...
    MiniBatchFormat=[format_x format_y], ...
    OutputEnvironment=["auto" "auto"]);
mbqTest = minibatchqueue(test_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFcn=@(x, y) makeOneHotSeqs(x, y), ...
    MiniBatchFormat=[format_x format_y], ...
    OutputEnvironment=["auto" "auto"]);
end