function [mbqTrain, mbqVal, mbqTest] = makeMBQs(train_ds, val_ds, test_ds, miniBatchSize, format_x, format_y)
mbqTrain = minibatchqueue(train_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=[format_x format_y], ...
    OutputEnvironment=["auto" "auto"]);
mbqVal = minibatchqueue(val_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=[format_x format_y], ...
    OutputEnvironment=["auto" "auto"]);
mbqTest = minibatchqueue(test_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=[format_x format_y], ...
    OutputEnvironment=["auto" "auto"]);
end