function [mbqTrain, mbqVal, mbqTest] = makeVoltageMBQsFrameWise(train_ds, val_ds, test_ds, miniBatchSize)
% MATLAB magic: Format as "SSBC" to get 32(S) × 31(S) × 1(C) × n(B)
mbqTrain = minibatchqueue(train_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=["SSBC" "CB"], ...
    OutputEnvironment=["gpu" "gpu"]);
mbqVal = minibatchqueue(val_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=["SSBC" "CB"], ...
    OutputEnvironment=["gpu" "gpu"]);
mbqTest = minibatchqueue(test_ds, ...
    MiniBatchSize=miniBatchSize, ...
    OutputAsDlarray=[1 1], ...
    MiniBatchFormat=["SSBC" "CB"], ...
    OutputEnvironment=["gpu" "gpu"]);
end